apiVersion: v1
kind: ConfigMap
metadata:
  name: logiflow-config
  namespace: logiflow
data:
  # PostgreSQL
  POSTGRES_USER: "logiflow"
  
  # RabbitMQ
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  
  # JWT
  JWT_EXPIRATION: "3600000"
  
  # Node.js
  NODE_ENV: "production"
