apiVersion: v1
kind: Secret
metadata:
  name: logiflow-secrets
  namespace: logiflow
type: Opaque
data:
  # Base64 encoded values
  # POSTGRES_PASSWORD: logiflow
  # RABBITMQ_PASSWORD: guest  
  # JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 (256-bit hex key)
  POSTGRES_PASSWORD: bG9naWZsb3c=
  RABBITMQ_PASSWORD: Z3Vlc3Q=
  JWT_SECRET: NDA0RTYzNTI2NjU1NkE1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MA==
